name: Build and Release

on:
 push:
  tags:
   - "v*"
 workflow_dispatch:

permissions:
 contents: write

jobs:
 verify:
  runs-on: ubuntu-latest

  steps:
   - uses: actions/checkout@v4

   - name: Read version
     id: ver
     run: echo "version=$(jq -r .version manifest.json)" >> $GITHUB_OUTPUT

   - name: Verify tag matches manifest.json version
     if: startsWith(github.ref, 'refs/tags/')
     run: |
      tag="${GITHUB_REF_NAME#v}"
      echo "Tag: $tag"
      echo "Manifest: ${{ steps.ver.outputs.version }}"
      if [ "$tag" != "${{ steps.ver.outputs.version }}" ]; then
        echo "Tag ($tag) does not match manifest.json version (${{ steps.ver.outputs.version }})" >&2
        exit 1
      fi
